*GeoJSON-Examples
barsLilleGJ
	^ '
	{
  "type": "FeatureCollection",
  "generator": "overpass-ide",
  "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.",
  "timestamp": "2021-07-15T08:57:00Z",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "@id": "node/617240502",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/amulsolorootsbar",
        "contact:housenumber": "9",
        "contact:phone": "+33 3 20 74 44 90",
        "contact:street": "Rue des Arts",
        "name": "Amul solo"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0666219,
          50.6380195
        ]
      },
      "id": "node/617240502"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/674884872",
        "addr:housenumber": "25",
        "addr:street": "Rue des Trois Mollettes",
        "amenity": "bar",
        "brewery": "chouffe;moinette;Pils de la Capsule",
        "name": "La Capsule",
        "name:en": "Capsule",
        "opening_hours": "Mo-We 17:30-01:00, Th,Fr 17:30-03:00, Sa 16:00-03:00, Su 17:30-24:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0601647,
          50.6405392
        ]
      },
      "id": "node/674884872"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/674884877",
        "addr:city": "Lille",
        "addr:housenumber": "41",
        "addr:postcode": "59000",
        "addr:street": "Rue Lepelletier",
        "amenity": "bar",
        "name": "Bar Parallèle",
        "opening_hours": "Tu,We 17:00-01:00; Th-Sa 17:00-03:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0621012,
          50.6388109
        ]
      },
      "id": "node/674884877"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1502852091",
        "amenity": "bar",
        "name": "Marvin s Bar",
        "source": "survey",
        "survey:date": "2018-01"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0517462,
          50.625715
        ]
      },
      "id": "node/1502852091"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1502852104",
        "amenity": "bar",
        "name": "Le Sérail (chicha)"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0520708,
          50.6253236
        ]
      },
      "id": "node/1502852104"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1505154841",
        "amenity": "bar",
        "contact:phone": "+33 3 20 54 67 34",
        "name": "Le Relax",
        "outdoor_seating": "yes",
        "source": "survey",
        "survey:date": "2018-01"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0493538,
          50.6255032
        ]
      },
      "id": "node/1505154841"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1525093496",
        "addr:city": "Lille",
        "addr:housenumber": "25",
        "addr:postcode": "59000",
        "addr:street": "Boulevard Jean-Baptiste Lebas",
        "amenity": "bar",
        "brewery": "chouffe;leffe",
        "name": "Le bistrot de st so",
        "opening_hours": "We,Th 11:30-23:00; Fr 11:30-24:00; Sa 00:00-01:00,11:30-24:00; Su 00:00-01:00,11:30-21:00",
        "phone": "+33320320542",
        "toilets:wheelchair": "yes",
        "website": "http://www.facebook.com/lebistrotdestso",
        "wheelchair": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.072063,
          50.6271741
        ]
      },
      "id": "node/1525093496"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1696043322",
        "addr:housenumber": "159",
        "addr:street": "Rue Solférino",
        "amenity": "bar",
        "name": "La Petite Loge",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0582751,
          50.6295412
        ]
      },
      "id": "node/1696043322"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1723969667",
        "amenity": "bar",
        "name": "Au bélier"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.090016,
          50.6763865
        ]
      },
      "id": "node/1723969667"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1723969685",
        "amenity": "bar",
        "name": "Le Nautic"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.09034,
          50.6762561
        ]
      },
      "id": "node/1723969685"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1770543273",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/Bar-Le-Point-G-115884263128154/",
        "contact:phone": "+33 3 20 52 79 88",
        "food": "yes",
        "name": "Le Point G",
        "opening_hours": "Tu-Th 11:30-14:00, 17:00-00:00; Fr 11:30-14:00, 17:00-01:00; Sa 17:00-01:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0685336,
          50.6292181
        ]
      },
      "id": "node/1770543273"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1780244102",
        "amenity": "bar",
        "name": "L intervalle bar"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0565641,
          50.6398695
        ]
      },
      "id": "node/1780244102"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2086382604",
        "addr:city": "Lille",
        "addr:country": "FR",
        "addr:housenumber": "1",
        "addr:postcode": "59000",
        "addr:street": "Rue de Douai",
        "amenity": "bar",
        "name": "Le Flint",
        "opening_hours:covid19": "open",
        "public_transport_network": "Transpole",
        "source": "cadastre-dgi-fr source : Direction Générale des Impôts - Cadastre. Mise à jour : 2012",
        "tickets:public_transport": "yes",
        "tobacco": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.068395,
          50.6241973
        ]
      },
      "id": "node/2086382604"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2090993678",
        "amenity": "bar",
        "name": "L Armoric"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0587624,
          50.6211041
        ]
      },
      "id": "node/2090993678"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2096356685",
        "addr:city": "Lille",
        "addr:housenumber": "19",
        "addr:postcode": "59000",
        "addr:street": "Boulevard Jean-Baptiste Lebas",
        "amenity": "bar",
        "brewery": "yes;various",
        "name": "La Mouss Touch",
        "outdoor_seating": "yes",
        "shop": "tobacco",
        "smoking": "outside",
        "source": "cadastre-dgi-fr source : Direction Générale des Impôts - Cadastre. Mise à jour : 2013",
        "wheelchair": "limited"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0698078,
          50.6271593
        ]
      },
      "id": "node/2096356685"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2096365210",
        "addr:city": "Lille",
        "addr:housenumber": "26",
        "addr:postcode": "59000",
        "addr:street": "Boulevard Jean-Baptiste Lebas",
        "amenity": "bar",
        "brewery": "Guinness",
        "name": "L Alchimiste",
        "opening_hours": "Mo-Su 17:00-24:00",
        "source": "cadastre-dgi-fr source : Direction Générale des Impôts - Cadastre. Mise à jour : 2013"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0681938,
          50.6269306
        ]
      },
      "id": "node/2096365210"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2194045043",
        "amenity": "bar",
        "name": "Au diable des plaisirs",
        "opening_hours": "Mo,Tu 11:00-14:00; We-Sa 11:00-14:00,19:00-22:00",
        "phone": "+33320008121",
        "website": "https://www.audiabledesplaisirs.fr/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0609787,
          50.628281
        ]
      },
      "id": "node/2194045043"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2212533769",
        "addr:city": "Lille",
        "addr:housenumber": "7",
        "addr:postcode": "59800",
        "addr:street": "Rue du Priez",
        "amenity": "bar",
        "contact:housenumber": "7",
        "cuisine": "french",
        "name": "Le Priez",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0684225,
          50.636379
        ]
      },
      "id": "node/2212533769"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2213796431",
        "amenity": "bar",
        "name": "La Mezza"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0609371,
          50.6421195
        ]
      },
      "id": "node/2213796431"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2242643746",
        "amenity": "bar",
        "contact:housenumber": "159",
        "contact:street": "Rue d Artois",
        "name": "L Imposture"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0613569,
          50.6194383
        ]
      },
      "id": "node/2242643746"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2295035005",
        "addr:city": "Lille",
        "addr:housenumber": "43",
        "addr:postcode": "59000",
        "addr:street": "Rue du Molinel",
        "amenity": "bar",
        "name": "Le Molinel",
        "tobacco": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0687716,
          50.6345782
        ]
      },
      "id": "node/2295035005"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2300194290",
        "amenity": "bar",
        "name": "Le Vega",
        "source": "local_knowledge"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0611798,
          50.6581065
        ]
      },
      "id": "node/2300194290"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2389886650",
        "amenity": "bar",
        "name": "omega",
        "tobacco": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0453976,
          50.6360563
        ]
      },
      "id": "node/2389886650"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2645425877",
        "addr:city": "Lille",
        "addr:housenumber": "11",
        "addr:postcode": "59800",
        "addr:street": "Place de la Gare",
        "amenity": "bar",
        "name": "Le Palais de la Bière",
        "opening_hours": "Mo-Sa 06:00-24:00; Su 07:00-24:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0694594,
          50.6369657
        ]
      },
      "id": "node/2645425877"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2694662653",
        "addr:city": "Lille",
        "addr:housenumber": "116",
        "addr:postcode": "59000",
        "addr:street": "Rue Pierre Legrand",
        "amenity": "bar",
        "name": "Alto Post"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0892872,
          50.632118
        ]
      },
      "id": "node/2694662653"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2776082397",
        "addr:housenumber": "175",
        "addr:street": "Rue Fénelon",
        "amenity": "bar",
        "name": "Au Bienvenue",
        "source": "cadastre-dgi-fr source : Direction Générale des Impôts - Cadastre. Mise à jour : 2014"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.1057153,
          50.6325878
        ]
      },
      "id": "node/2776082397"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2815355416",
        "amenity": "bar",
        "name": "La Boulangerie: pétrissage de baguettes & de miches",
        "opening_hours": "Mo-Th 16:00-24:00, Fr 16:00-01:00, Sa 16:00-02:00, Su 16:00-23:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0574893,
          50.6277019
        ]
      },
      "id": "node/2815355416"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2899437007",
        "amenity": "bar",
        "name": "Kee Mao Bar"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0519524,
          50.6284695
        ]
      },
      "id": "node/2899437007"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/2899737771",
        "addr:city": "Lille",
        "addr:housenumber": "34",
        "addr:postcode": "59800",
        "addr:street": "Rue des Bouchers",
        "amenity": "bar",
        "name": "Chez Paulette",
        "phone": "+33 6 30 55 86 60",
        "smoking": "outside",
        "source": "cadastre-dgi-fr source : Direction Générale des Finances Publiques - Cadastre. Mise à jour : 2014"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.058256,
          50.6378968
        ]
      },
      "id": "node/2899737771"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3021793000",
        "amenity": "bar",
        "contact:phone": "+33 9 88 00 46 29",
        "contact:website": "https://www.bistrot-brigand.com/",
        "food": "yes",
        "name": "Brigand",
        "opening_hours": "Tu-Fr 12:00-14:30,18:00-00:00; Sa 18:00-01:00",
        "wheelchair": "limited"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0614214,
          50.6335821
        ]
      },
      "id": "node/3021793000"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3021793011",
        "amenity": "bar",
        "brewery": "Kasteel;Chouffe;Paix Dieu;La corne",
        "contact:facebook": "https://www.facebook.com/B148ThePlaceToBeer/",
        "name": "B148",
        "opening_hours": "Mo-Th 16:00-24:00; Fr 16:00-01:00; Sa 16:00-02:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0636431,
          50.6327063
        ]
      },
      "id": "node/3021793011"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3097371786",
        "amenity": "bar",
        "name": "L Addict",
        "old_name": "La Cave de Moulins",
        "source": "survey 2014"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0714904,
          50.6241609
        ]
      },
      "id": "node/3097371786"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3120124169",
        "amenity": "bar",
        "name": "Ô Toulouse"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0407916,
          50.6228683
        ]
      },
      "id": "node/3120124169"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3120324641",
        "addr:city": "Lille",
        "addr:housenumber": "33",
        "addr:postcode": "59000",
        "addr:street": "Rue des Bouchers",
        "amenity": "bar",
        "name": "Dame C"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0584176,
          50.6380012
        ]
      },
      "id": "node/3120324641"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3121907989",
        "amenity": "bar",
        "brewery": "Hommel bier",
        "name": "Café Jean"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0548204,
          50.6239996
        ]
      },
      "id": "node/3121907989"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3141453022",
        "amenity": "bar",
        "name": "River Gambia"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0525541,
          50.6232593
        ]
      },
      "id": "node/3141453022"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3145554688",
        "amenity": "bar",
        "brewery": "leffe",
        "internet_access": "no",
        "loc_name": "Chez Rosie",
        "name": "L Indigo Bar"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0560657,
          50.6255775
        ]
      },
      "id": "node/3145554688"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3270454487",
        "amenity": "bar",
        "name": "ingenue"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0578561,
          50.627736
        ]
      },
      "id": "node/3270454487"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3270477661",
        "amenity": "bar",
        "name": "La Chapelle à ma Tante",
        "opening_hours": "Mo,Tu 16:00-01:00, We 18:00-01:00, Th,Fr 18:00-03:00, Sa 11:00-03:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0583491,
          50.6283633
        ]
      },
      "id": "node/3270477661"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3342252710",
        "addr:city": "Lambersart",
        "addr:housenumber": "32",
        "addr:postcode": "59130",
        "addr:street": "Avenue Becquart",
        "amenity": "bar",
        "amenity_1": "restaurant",
        "name": "Le Victoria"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0398774,
          50.6496553
        ]
      },
      "id": "node/3342252710"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3381342633",
        "addr:housenumber": "2",
        "amenity": "bar",
        "name": "Chez Philippe",
        "source": "cadastre-dgi-fr source : Direction Générale des Impôts - Cadastre. Mise à jour : 2015"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.102897,
          50.6341892
        ]
      },
      "id": "node/3381342633"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3390290599",
        "addr:city": "Lomme",
        "addr:housenumber": "355",
        "addr:postcode": "59160",
        "addr:street": "Avenue de Dunkerque",
        "amenity": "bar",
        "name": "Au Stop"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0182519,
          50.6410436
        ]
      },
      "id": "node/3390290599"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/3602020402",
        "addr:city": "Lille",
        "addr:housenumber": "385",
        "addr:postcode": "59000",
        "addr:street": "Rue Léon Gambetta",
        "amenity": "bar",
        "brewery": "Hommel",
        "internet_access": "no",
        "name": "Uno s Bar",
        "opening_hours": "Tu-Th 15:00-00:00; Fr-Sa 15:00-01:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0468114,
          50.6261186
        ]
      },
      "id": "node/3602020402"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4024966414",
        "amenity": "bar",
        "contact:housenumber": "286",
        "happy_hours": "Mo-Su 16:00-20:00",
        "name": "L Appart Café",
        "note": "Biere: 4.50(5.50) Cocktail: 6:00(7:00) soft: 2:50(3:00)",
        "opening_hours": "Mo-We 16:00-01:00; Th-Fr 16:00-03:00; Sa 18:00-03:00",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.045995,
          50.6301341
        ]
      },
      "id": "node/4024966414"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4161754229",
        "amenity": "bar",
        "contact:housenumber": "5",
        "contact:phone": "+33 6 60 44 65 73",
        "contact:website": "https://www.monsieur-lezinc.com/m-le-zinc-lille-nord",
        "name": "Monsieur le Zinc"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0537089,
          50.6328101
        ]
      },
      "id": "node/4161754229"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4202338993",
        "addr:city": "Lesquin",
        "addr:housenumber": "2",
        "addr:postcode": "59810",
        "addr:street": "Rue des Meuniers",
        "amenity": "bar",
        "contact:email": "zen-wok@hotmail.com",
        "contact:phone": "+33 3 20 58 48 88",
        "name": "Zen-Wok",
        "opening_hours": "Mo-Sa 12:00-14:30, 19:00-22:30; Su 12:00-14:30",
        "website": "http://www.zen-wok.fr/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0877868,
          50.5895119
        ]
      },
      "id": "node/4202338993"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4236323817",
        "addr:city": "Lille",
        "addr:housenumber": "17",
        "addr:postcode": "59000",
        "addr:street": "Place de la Gare",
        "amenity": "bar",
        "name": "Le Napoléon",
        "opening_hours": "Mo-Su 10:30-24:00",
        "outdoor_seating": "yes",
        "source": "survey"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0697362,
          50.6370922
        ]
      },
      "id": "node/4236323817"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4236323818",
        "addr:city": "Lille",
        "addr:housenumber": "15",
        "addr:postcode": "59800",
        "addr:street": "Place de la Gare",
        "amenity": "bar",
        "name": "Taverne Flamande",
        "opening_hours": "Mo-Fr 06:30-24:00; Sa 06:30-02:00; Su 10:00-24:00",
        "outdoor_seating": "yes",
        "source": "survey"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0696177,
          50.6370267
        ]
      },
      "id": "node/4236323818"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4237396196",
        "amenity": "bar",
        "contact:housenumber": "10",
        "contact:phone": "+33 320513063",
        "contact:street": "Rue du Pont Neuf",
        "contact:website": "http://www.beerstro.fr/",
        "name": "Beerstro",
        "opening_hours": "Su-Th 12:00-00:00; Fr 12:00-01:0; Sa 12:00-02:00",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.060666,
          50.6432293
        ]
      },
      "id": "node/4237396196"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4335499830",
        "addr:city": "Lille",
        "addr:housenumber": "42",
        "addr:postcode": "59000",
        "addr:street": "Rue Saint-Sébastien",
        "amenity": "bar",
        "internet_access": "wlan",
        "name": "L embuscade"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0579201,
          50.6468914
        ]
      },
      "id": "node/4335499830"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421739669",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/DisrespectLille/",
        "contact:housenumber": "6",
        "name": "Disrespect",
        "opening_hours": "Tu-Th 17:00-00:00; Fr 17:00-01:00; Sa 17:00-02:00; Su 16:00-23:00",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0535609,
          50.6327084
        ]
      },
      "id": "node/4421739669"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421747216",
        "addr:city": "Lille",
        "addr:housenumber": "20",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Temple s Bar",
        "opening_hours": "Mo 17:00-03:00; Tu 17:00-01:00; We-Su 17:00-03:00",
        "outdoor_seating": "yes",
        "phone": "+333 20 77 91 34"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0548362,
          50.6329778
        ]
      },
      "id": "node/4421747216"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421774637",
        "addr:city": "Lille",
        "addr:housenumber": "32",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "La Boucherie",
        "opening_hours": "We-Sa 20:00-07:00",
        "outdoor_seating": "no",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0548587,
          50.6327132
        ]
      },
      "id": "node/4421774637"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421774638",
        "addr:city": "Lille",
        "addr:housenumber": "40",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Le Sherwood",
        "opening_hours": "Mo-Su 16:00-03:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0548384,
          50.6326206
        ]
      },
      "id": "node/4421774638"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421774639",
        "addr:city": "Lille",
        "addr:housenumber": "42",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Le Latina Cafe"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.054829,
          50.6325503
        ]
      },
      "id": "node/4421774639"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421806113",
        "addr:city": "Lille",
        "addr:street": "Rue Meurein",
        "amenity": "bar",
        "name": "LouLou",
        "opening_hours": "Mo-Su 17:00-00:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0485289,
          50.6324286
        ]
      },
      "id": "node/4421806113"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421814905",
        "addr:city": "Lille",
        "addr:housenumber": "31",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Le décalé",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0551417,
          50.6328507
        ]
      },
      "id": "node/4421814905"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421814906",
        "addr:city": "Lille",
        "addr:housenumber": "23",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Shooter s Bar",
        "opening_hours": "Mo-Sa 16:00-03:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0551529,
          50.6329474
        ]
      },
      "id": "node/4421814906"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421814908",
        "addr:city": "Lille",
        "addr:housenumber": "39",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Trading Bar",
        "opening_hours": "We, Th, Su 20:00-00:00; Sa 20:00-02:00",
        "outdoor_seating": "yes",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.055122,
          50.6327054
        ]
      },
      "id": "node/4421814908"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421814909",
        "addr:city": "Lille",
        "addr:housenumber": "43",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Pacha Bar",
        "opening_hours": "Mo-Th 15:00-00:00; Fr 15:00-01:00; Sa 15:00-02:00; Su 15:00-01:00",
        "outdoor_seating": "no",
        "prix_demi": "3€",
        "prix_pinte": "4,5€"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0551099,
          50.6326348
        ]
      },
      "id": "node/4421814909"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421814910",
        "addr:city": "Lille",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "brewery": "Hommel Bier;LeFort;Cuvée Des Trolls",
        "contact:facebook": "https://www.facebook.com/Speakeasylille/",
        "name": "Le SpeakEasy",
        "opening_hours": "Tu-We 17:00-01:00; Th-Sa 17:00-03:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0550999,
          50.6325186
        ]
      },
      "id": "node/4421814910"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421852120",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/MojiitoPubLille/",
        "contact:housenumber": "44",
        "name": "Mojito Pub",
        "source": "survey",
        "survey:date": "2018-06"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0552466,
          50.6323871
        ]
      },
      "id": "node/4421852120"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4421954776",
        "amenity": "bar",
        "name": "L imprévu"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0548929,
          50.6331955
        ]
      },
      "id": "node/4421954776"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4422083927",
        "addr:city": "Lille",
        "addr:housenumber": "26",
        "addr:postcode": "59000",
        "addr:street": "Rue des Stations",
        "amenity": "bar",
        "name": "Le Bar des Six Roses",
        "opening_hours": "Mo-Th 18:00-0:00,Fr 18:00-1:00,Sa 18:00-2:00,Su 18:00-1:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0522265,
          50.6310924
        ]
      },
      "id": "node/4422083927"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4422083929",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/Le-B%C3%B4-Bar-448031448878881/",
        "contact:housenumber": "219",
        "name": "Le Bô Bar",
        "opening_hours": "Mo-Th 09:00-00:00; Fr 09:00-01:00; Sa 09:00-02:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0495596,
          50.6312948
        ]
      },
      "id": "node/4422083929"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4422191479",
        "addr:city": "Lille",
        "addr:housenumber": "15",
        "addr:postcode": "59000",
        "addr:street": "Rue du Faisan",
        "amenity": "bar",
        "name": "Le Network",
        "opening_hours": "Tu-Sa 22:30-7:00; Th 21:30-7:00; Su 19:00-7:00",
        "phone": "+33 3 20 40 04 91"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0540985,
          50.6326178
        ]
      },
      "id": "node/4422191479"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4422206341",
        "addr:city": "Lille",
        "addr:housenumber": "57",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Magnum Café",
        "opening_hours": "Mo-Su 15:00-03:00",
        "outdoor_seating": "yes",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0550752,
          50.6323149
        ]
      },
      "id": "node/4422206341"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4422206342",
        "amenity": "bar",
        "contact:housenumber": "59",
        "contact:street": "Rue Masséna",
        "hh_hours": "Mon-Sun: 18:00-20:00",
        "name": "Zythum",
        "opening_hours": "Mo-Th 15:00-00:00; Fr 15:00-01:00; Sa 15:00-02:00; Su 15:00-01:00",
        "outdoor_seating": "yes",
        "phone": "+333 62 65 72 38",
        "prix_cocktail": "6€",
        "prix_cocktail_hh": "5€",
        "prix_demi": "2,7€",
        "prix_pinte": "5€",
        "prix_pinte_hh": "2,9€",
        "prix_soft": "3€",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0550568,
          50.6320211
        ]
      },
      "id": "node/4422206342"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4422206343",
        "addr:city": "Lille",
        "addr:housenumber": "12",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Bar O Nours",
        "opening_hours": "Mo 08:00-20:00; Tu-Th 08:00-22:00; Fr 08:00-00:00; Sa 09:00-00:00",
        "outdoor_seating": "yes",
        "smoking": "outside",
        "website": "http://o-nours.com/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0549443,
          50.6333627
        ]
      },
      "id": "node/4422206343"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4422227529",
        "addr:city": "Lille",
        "addr:housenumber": "14",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "La Relève",
        "opening_hours": "We-Sa 23:00-07:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0549429,
          50.6332982
        ]
      },
      "id": "node/4422227529"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4422227530",
        "addr:city": "Lille",
        "addr:housenumber": "8",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Razorback",
        "opening_hours": "Tu-Su 17:00 - 03:00",
        "outdoor_seating": "no",
        "phone": "+33 3 20 63 28 35"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0549639,
          50.6334375
        ]
      },
      "id": "node/4422227530"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4423709509",
        "addr:city": "Lille",
        "addr:housenumber": "7",
        "addr:postcode": "59000",
        "addr:street": "Place de Strasbourg",
        "amenity": "bar",
        "name": "Le Rendez-Vous",
        "opening_hours": "Tu-Sa 18:00-03:00",
        "outdoor_seating": "yes",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0552532,
          50.6335534
        ]
      },
      "id": "node/4423709509"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4423782180",
        "addr:city": "Lille",
        "addr:housenumber": "3",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Base Camp",
        "opening_hours": "Mo-We 17:00-01:00; Th-Sa 17:00-03:00",
        "outdoor_seating": "yes",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0552345,
          50.6334665
        ]
      },
      "id": "node/4423782180"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4423782181",
        "addr:city": "Lille",
        "addr:housenumber": "21",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "O Corner",
        "opening_hours": "Tu-We 17:00-02:00; Th-Sa 17:00-07:00",
        "outdoor_seating": "no",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0551955,
          50.6331117
        ]
      },
      "id": "node/4423782181"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4425453061",
        "amenity": "bar",
        "contact:housenumber": "136",
        "name": "Tcha Tcha",
        "note": "Happy hour: 18:00-21:00 1 cocktail=1shooter",
        "opening_hours": "Tu-We 18:00-01:00, Th-Sa 18:00-03:00, Su-Mo 19:00-01:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.053509,
          50.631755
        ]
      },
      "id": "node/4425453061"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4426552549",
        "amenity": "bar",
        "contact:housenumber": "138",
        "name": "L atomic",
        "opening_hours": "Mo-Sa 18:00-03:00; Su 20:00-03:00",
        "phone": "+33 3 20 40 18 49"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0535729,
          50.6317247
        ]
      },
      "id": "node/4426552549"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4431625184",
        "amenity": "bar",
        "contact:housenumber": "122bis",
        "name": "La Plage",
        "opening_hours": "Tu-Sa 18:00-03:00",
        "phone": "+333 20 13 98 04"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0529202,
          50.6320874
        ]
      },
      "id": "node/4431625184"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4431625185",
        "addr:city": "Lille",
        "addr:housenumber": "156",
        "addr:postcode": "59000",
        "addr:street": "Rue Solférino",
        "amenity": "bar",
        "name": "Le Solférino",
        "opening_hours": "Mo-We 07:00-01:00; Th-Sa 07:00-03:00; Su 09:00-01:00",
        "opening_hours:covid19": "same",
        "outdoor_seating": "yes",
        "phone": "+333 20 57 03 43",
        "shop": "tobacco",
        "tobacco": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0546207,
          50.6311763
        ]
      },
      "id": "node/4431625185"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432645619",
        "addr:city": "Lille",
        "addr:housenumber": "13",
        "addr:postcode": "59800",
        "addr:street": "Rue Philippe-Laurent Roland",
        "amenity": "bar",
        "name": "La garderie",
        "opening_hours": "Mo-Th 14:00-00:00; Fr 14:00-01:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0420848,
          50.6320107
        ]
      },
      "id": "node/4432645619"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432667906",
        "addr:city": "Lille",
        "addr:housenumber": "166",
        "addr:postcode": "59000",
        "addr:street": "Rue Colbert",
        "amenity": "bar",
        "name": "B-Routh",
        "opening_hours": "Mo- Sa 11:00-00:00; Su 07:00-12:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0427022,
          50.6323407
        ]
      },
      "id": "node/4432667906"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432698857",
        "amenity": "bar",
        "name": "Chez Madeleine",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0499495,
          50.6267192
        ]
      },
      "id": "node/4432698857"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432698858",
        "amenity": "bar",
        "contact:facebook": "https://fr-fr.facebook.com/absurde.wzm",
        "contact:housenumber": "11",
        "name": "L absurde",
        "opening_hours": "Mo,We 10:00-00:00; Tu,Th 11:00-00:00; Fr 15:00-01:00; Sa 18:00-02:00; Su 11:00-23:00",
        "outdoor_seating": "yes",
        "source": "survey",
        "survey:date": "2018-01"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0498483,
          50.6268771
        ]
      },
      "id": "node/4432698858"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432698859",
        "amenity": "bar",
        "name": "la Craft Touch",
        "survey:date": "2019-12"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0498268,
          50.6269162
        ]
      },
      "id": "node/4432698859"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432765849",
        "addr:city": "Lille",
        "addr:housenumber": "13",
        "addr:postcode": "59000",
        "addr:street": "Rue Masséna",
        "amenity": "bar",
        "name": "Brooklyn Bar",
        "opening_hours": "Su-We 18:00-01:00, Th-Sa 18:00-03:00",
        "outdoor_seating": "no"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0552204,
          50.6332814
        ]
      },
      "id": "node/4432765849"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432802847",
        "amenity": "bar",
        "name": "Les Tilleuls",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0505749,
          50.6267621
        ]
      },
      "id": "node/4432802847"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432802848",
        "addr:city": "Lille",
        "addr:housenumber": "21",
        "addr:postcode": "59000",
        "addr:street": "Rue Saint-Pierre Saint-Paul",
        "amenity": "bar",
        "name": "L Oxford",
        "opening_hours": "Mo-Sa 16:00-00:00; Su 06:30-16:30",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0503143,
          50.626692
        ]
      },
      "id": "node/4432802848"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432802849",
        "addr:city": "Lille",
        "addr:housenumber": "16",
        "addr:postcode": "59000",
        "addr:street": "Rue des Sarrazins",
        "amenity": "bar",
        "name": "Chez Ben",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0504789,
          50.6255731
        ]
      },
      "id": "node/4432802849"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432802850",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/ChougaBarrioClub/?",
        "contact:housenumber": "32",
        "contact:street": "Rue des Sarrazins",
        "food": "yes",
        "name": "Chouga Barrio",
        "opening_hours": "Tu 10:00-14:00,17:30-16:00; We 17:30-00:00; Th 10:00-14:00,17:30-23:45; Fr 17:30-01:00; Sa 17:00-02:00; Su 09:00-22:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0496377,
          50.625416
        ]
      },
      "id": "node/4432802850"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432802851",
        "addr:city": "Lille",
        "addr:housenumber": "56",
        "addr:postcode": "59000",
        "addr:street": "Rue des Sarrazins",
        "amenity": "bar",
        "name": "Au Cheval Blanc",
        "opening_hours": "Mo-Sa 09:00-20:00",
        "outdoor_seating": "yes",
        "wheelchair": "no"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0486459,
          50.6251385
        ]
      },
      "id": "node/4432802851"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432802852",
        "addr:city": "Lille",
        "addr:housenumber": "25",
        "addr:postcode": "59000",
        "addr:street": "Rue des Sarrazins",
        "amenity": "bar",
        "name": "Le Bartabas",
        "opening_hours": "Tu-Su 09:00-23:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0479967,
          50.625061
        ]
      },
      "id": "node/4432802852"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432830120",
        "addr:street": "Rue de Pas",
        "amenity": "bar",
        "contact:housenumber": "12",
        "email": "lille@dernierbar.com",
        "name": "Dernier Bar avant la Fin du Monde",
        "opening_hours": "Mo-Fr 14:00-01:00; Sa 14:00-02:00; Su 14:00-22:00",
        "outdoor_seating": "yes",
        "phone": "+33 3 61 50 43 20",
        "smoking": "outside",
        "website": "http://lille.dernierbar.com/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0613923,
          50.6372976
        ]
      },
      "id": "node/4432830120"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432830121",
        "addr:city": "Lille",
        "addr:housenumber": "2",
        "addr:postcode": "59000",
        "addr:street": "Rue Royale",
        "amenity": "bar",
        "name": "Le Privilège",
        "opening_hours": "Mo-Sa 15:00-03:00;Su 17:00-03:00",
        "outdoor_seating": "no"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0587377,
          50.6390592
        ]
      },
      "id": "node/4432830121"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432830122",
        "addr:city": "Lille",
        "addr:housenumber": "8",
        "addr:postcode": "59000",
        "addr:street": "Rue Royale",
        "amenity": "bar",
        "name": "Le Bellerose",
        "opening_hours": "Mo-Th 11:00-00:00;Fr 11:00-01:00;Sa 11:00-02:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0586374,
          50.6391849
        ]
      },
      "id": "node/4432830122"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432830123",
        "addr:city": "Lille",
        "addr:housenumber": "10",
        "addr:postcode": "59800",
        "addr:street": "Rue Royale",
        "amenity": "bar",
        "name": "Le Lobby",
        "opening_hours": "Mo-We,Su 17:00-01:00;Th-Sa 17:00-03:00",
        "outdoor_seating": "no"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0586026,
          50.6392361
        ]
      },
      "id": "node/4432830123"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432846595",
        "addr:city": "Lille",
        "addr:housenumber": "14",
        "addr:postcode": "59800",
        "addr:street": "Rue Royale",
        "amenity": "bar",
        "name": "L Autrement Dit",
        "opening_hours": "Mo-Th 10:00-01:00; Fr 10:00-03:00; Sa 15:00-03:00; Su 16:00-01:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0585474,
          50.639328
        ]
      },
      "id": "node/4432846595"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4432846596",
        "addr:city": "Lille",
        "addr:housenumber": "16",
        "addr:postcode": "59000",
        "addr:street": "Rue Royale",
        "amenity": "bar",
        "fixme": "Horaires d ouverture à compléter",
        "name": "Le BAM",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0585167,
          50.6393705
        ]
      },
      "id": "node/4432846596"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4442146052",
        "addr:city": "Lille",
        "addr:housenumber": "26",
        "addr:postcode": "59000",
        "addr:street": "Place de la Gare",
        "amenity": "bar",
        "name": "Le QG",
        "opening_hours": "Mo-Sa 09:30-00:00",
        "outdoor_seating": "yes",
        "phone": "+33 3 20 63 20 20"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0694346,
          50.6360788
        ]
      },
      "id": "node/4442146052"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4442146053",
        "addr:city": "Lille",
        "addr:housenumber": "50",
        "addr:postcode": "59800",
        "addr:street": "Place de la Gare",
        "amenity": "bar",
        "name": "L Express",
        "opening_hours": "Mo-Th,Su 07:00-00:00; Fr-Sa 07:00-01:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0700555,
          50.6357105
        ]
      },
      "id": "node/4442146053"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4442146054",
        "addr:city": "Lille",
        "addr:housenumber": "8",
        "addr:postcode": "59000",
        "addr:street": "Rue du Molinel",
        "amenity": "bar",
        "name": "Au Courrier de Tournai",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.069929,
          50.635592
        ]
      },
      "id": "node/4442146054"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4442146055",
        "addr:city": "Lille",
        "addr:housenumber": "16",
        "addr:postcode": "59800",
        "addr:street": "Rue du Molinel",
        "amenity": "bar",
        "name": "Paris Nord",
        "operator": "Mon-Fri 07:00-19:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0698725,
          50.6355021
        ]
      },
      "id": "node/4442146055"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4442146056",
        "addr:city": "Lille",
        "addr:housenumber": "6",
        "addr:postcode": "59800",
        "addr:street": "Rue de Tournai",
        "amenity": "bar",
        "name": "Au Lion Belge",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0705534,
          50.6354038
        ]
      },
      "id": "node/4442146056"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4445182608",
        "addr:city": "Lille",
        "addr:housenumber": "41",
        "addr:postcode": "59000",
        "addr:street": "Rue de Puebla",
        "amenity": "bar",
        "name": "Tam-Tam",
        "opening_hours": "Su-We 17:00-01:00; Th-Sa 17:00-03:00",
        "phone": "+33 3 28 52 47 30"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0557331,
          50.6323671
        ]
      },
      "id": "node/4445182608"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4509014825",
        "addr:city": "Lille",
        "addr:housenumber": "71",
        "addr:postcode": "59000",
        "addr:street": "Rue Jeanne d Arc",
        "amenity": "bar",
        "diet:vegan": "only",
        "diet:vegetarian": "yes",
        "name": "Liquium",
        "opening_hours": "Tu-Th 12:00-24:00, Fr 12:00-01:00, Sa 18:00-02:00, Mo 17:00-24:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0644081,
          50.6242329
        ]
      },
      "id": "node/4509014825"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4570277277",
        "addr:city": "Lille",
        "addr:housenumber": "30",
        "addr:postcode": "59000",
        "addr:street": "Rue des Postes",
        "amenity": "bar",
        "name": "Au bout du bar"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0573159,
          50.6275104
        ]
      },
      "id": "node/4570277277"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4678709689",
        "addr:postcode": "59800",
        "amenity": "bar",
        "name": "Stairway",
        "opening_hours": "Tu-Th 18:00-03:00; Fr-Sa 18:00-06:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0605584,
          50.644886
        ]
      },
      "id": "node/4678709689"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/4974260621",
        "addr:housenumber": "29",
        "addr:street": "Place Louise de Bettignies",
        "amenity": "bar",
        "name": "Joker Bar"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0647064,
          50.6410096
        ]
      },
      "id": "node/4974260621"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5006338521",
        "amenity": "bar",
        "contact:phone": "+33 3 20 55 73 25",
        "name": "La Faluche",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0445096,
          50.6335256
        ]
      },
      "id": "node/5006338521"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5046183224",
        "amenity": "bar",
        "name": "Au 210"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0137877,
          50.6533507
        ]
      },
      "id": "node/5046183224"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5058070123",
        "addr:city": "Lille",
        "addr:housenumber": "11",
        "addr:postcode": "59000",
        "addr:street": "Place Pierre Mendès France",
        "amenity": "bar",
        "name": "Bistrot du Nouveau Siècle",
        "opening_hours": "Mo-Su 09:00-01:00",
        "outdoor_seating": "yes",
        "phone": "+33 3 20 15 17 67",
        "smoking": "outside",
        "website": "https://www.facebook.com/pg/bistrotdunouveausiecle/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0607217,
          50.6372379
        ]
      },
      "id": "node/5058070123"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5075121572",
        "amenity": "bar",
        "name": "Le Fontenoy"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.1126388,
          50.6293095
        ]
      },
      "id": "node/5075121572"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5075121573",
        "amenity": "bar",
        "name": "Le 54"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.1115537,
          50.6279917
        ]
      },
      "id": "node/5075121573"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5077789123",
        "addr:housenumber": "12",
        "addr:postcode": "59000",
        "addr:street": "Rue Royale",
        "amenity": "bar",
        "name": "Maison blanche",
        "name:fr": "Maison blanche",
        "opening_hours": "Mo-Sa 11:00-00:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0582756,
          50.6389171
        ]
      },
      "id": "node/5077789123"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5101761972",
        "amenity": "bar",
        "name": "JaJa",
        "website": "https://www.facebook.com/JajaLille"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0585363,
          50.6440401
        ]
      },
      "id": "node/5101761972"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5109177874",
        "addr:housenumber": "42",
        "addr:street": "Rue des Postes",
        "amenity": "bar",
        "email": "lokarria.bar@gmail.com",
        "level": "0",
        "name": "Lokarria",
        "operator": "GIZARTE LOKARRIA SARL",
        "phone": "+33362645543"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0570218,
          50.6271622
        ]
      },
      "id": "node/5109177874"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5116121632",
        "amenity": "bar",
        "name": "La Taverne d Alissa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0695596,
          50.6567533
        ]
      },
      "id": "node/5116121632"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5135489624",
        "addr:housenumber": "14",
        "addr:postcode": "59800",
        "addr:street": "Rue au Péterinck",
        "amenity": "bar",
        "internet_access": "wlan",
        "name": "Bibo Vino",
        "opening_hours": "Tu-Sa 11:00-23:00",
        "phone": "+33 3 59 51 59 02",
        "website": "http://bibovino.fr"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0615909,
          50.6411013
        ]
      },
      "id": "node/5135489624"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5163090880",
        "amenity": "bar",
        "name": "Le St 21",
        "source": "survey",
        "survey:date": "2017-10"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0610093,
          50.6368218
        ]
      },
      "id": "node/5163090880"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5163090884",
        "addr:city": "Lille",
        "addr:housenumber": "331",
        "addr:postcode": "59000",
        "addr:street": "Rue Léon Gambetta",
        "amenity": "bar",
        "name": "Le Brice",
        "source": "survey"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0496924,
          50.6272787
        ]
      },
      "id": "node/5163090884"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5163090893",
        "amenity": "bar",
        "name": "Le Point de Départ",
        "source": "survey",
        "survey:date": "2017-10"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0476278,
          50.6348714
        ]
      },
      "id": "node/5163090893"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5163090899",
        "amenity": "bar",
        "name": "Splin Lounge Bar",
        "source": "survey",
        "survey:date": "2017-10"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0559608,
          50.6304838
        ]
      },
      "id": "node/5163090899"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5163093745",
        "amenity": "bar",
        "name": "Le Rallye",
        "source": "survey",
        "survey:date": "2017-10"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0589568,
          50.6310839
        ]
      },
      "id": "node/5163093745"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5202358159",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/Barber-Bar-1142910719063311/",
        "name": "Barber Bar",
        "source": "survey",
        "survey:date": "2017-10"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0546123,
          50.6323209
        ]
      },
      "id": "node/5202358159"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5202358162",
        "amenity": "bar",
        "name": "Huit Bar",
        "source": "survey",
        "survey:date": "2017-10"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0536829,
          50.6325927
        ]
      },
      "id": "node/5202358162"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5202358166",
        "amenity": "bar",
        "name": "Seven Bar",
        "survey:date": "2020-02"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0529839,
          50.6320596
        ]
      },
      "id": "node/5202358166"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5225103902",
        "addr:city": "Mons-en-Barœul",
        "addr:country": "FR",
        "addr:housenumber": "119",
        "amenity": "bar",
        "name": "Le Lutecia"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.1143473,
          50.6352981
        ]
      },
      "id": "node/5225103902"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5225103903",
        "addr:housenumber": "204",
        "addr:street": "Rue Jacquard",
        "amenity": "bar",
        "name": "Les hirondelles"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.1134881,
          50.6352357
        ]
      },
      "id": "node/5225103903"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5226716622",
        "addr:city": "Lille",
        "addr:housenumber": "52",
        "addr:postcode": "59800",
        "addr:street": "Rue de la Clef",
        "amenity": "bar",
        "name": "Le Barillet",
        "toilets:wheelchair": "no",
        "wheelchair": "no"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.06496,
          50.639246
        ]
      },
      "id": "node/5226716622"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5287409055",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/lapepite/",
        "contact:phone": "+33 3 20 40 24 80",
        "food": "yes",
        "name": "La Pépite",
        "opening_hours": "Tu-Th 17:00-00:00; Fr 17:00-01:00; Sa 17:00-02:00; Su 15:00-22:00",
        "outdoor_seating": "yes",
        "survey:date": "2019-01"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0580485,
          50.6284311
        ]
      },
      "id": "node/5287409055"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5287465805",
        "amenity": "bar",
        "name": "Karafun"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0557979,
          50.6302529
        ]
      },
      "id": "node/5287465805"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5292504243",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/windsorbarlille/",
        "contact:phone": "+33 3 61 50 34 60",
        "name": "Le Windsor",
        "source": "survey"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0622644,
          50.6365972
        ]
      },
      "id": "node/5292504243"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5316414390",
        "addr:city": "Lille",
        "addr:housenumber": "92",
        "addr:postcode": "59800",
        "addr:street": "Rue Colbert",
        "amenity": "bar",
        "contact:phone": "+33 9 54 90 18 53",
        "contact:website": "https://barlespirateslille.wordpress.com/",
        "name": "Les pirates",
        "opening_hours": "Mo-Sa 16:30-01:00",
        "source": "survey"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0452394,
          50.6299407
        ]
      },
      "id": "node/5316414390"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5324577313",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/inreallifelille/",
        "contact:housenumber": "141",
        "name": "In Real Life",
        "opening_hours": "Mo-Tu 17:15-00:00; Fr 17:15-01:00; Sa 17:15-02:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0575657,
          50.6299056
        ]
      },
      "id": "node/5324577313"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5325754225",
        "amenity": "bar",
        "name": "Café Aux Halles",
        "outdoor_seating": "yes",
        "source": "survey",
        "survey:date": "2018-01"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0499714,
          50.6266866
        ]
      },
      "id": "node/5325754225"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5325754258",
        "amenity": "bar",
        "name": "Le Maryland",
        "source": "survey"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0491258,
          50.625866
        ]
      },
      "id": "node/5325754258"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5348005763",
        "addr:city": "Lille",
        "addr:housenumber": "7",
        "addr:postcode": "59000",
        "addr:street": "Rue du Vieux Faubourg",
        "amenity": "bar",
        "name": "Le vieux faubourg",
        "phone": "+33 3 20 06 06 81",
        "source": "survey"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0692692,
          50.6375737
        ]
      },
      "id": "node/5348005763"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5361882734",
        "addr:city": "Lille",
        "addr:housenumber": "197",
        "addr:postcode": "59000",
        "addr:street": "Rue des Bois Blancs",
        "amenity": "bar",
        "name": "Le Saint-Charles"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0260505,
          50.6311944
        ]
      },
      "id": "node/5361882734"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5361882735",
        "amenity": "bar",
        "description:covid19": "changement de propriétaire en cours",
        "name": "Le Chiquito",
        "opening_hours": "Sa 09:00-14:00, 16:30-19:30; Mo-Tu, Th-Fr 07:30-14:00, 16:00-19:30; Su 09:00-14:00",
        "tobacco": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0271315,
          50.6317917
        ]
      },
      "id": "node/5361882735"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5383854286",
        "amenity": "bar",
        "name": "Cafe Society",
        "source": "survey",
        "survey:date": "2018-02"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0639162,
          50.6372964
        ]
      },
      "id": "node/5383854286"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5383857935",
        "amenity": "bar",
        "name": "Le Pacha",
        "opening_hours": "Mo-Fr 09:00-18:00",
        "source": "survey",
        "tobacco": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0572127,
          50.6346128
        ]
      },
      "id": "node/5383857935"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5383857951",
        "amenity": "bar",
        "name": "La Manufacture",
        "opening_hours": "Mo-Th 14:00-24:00, Fr 14:00-01:00, Sa 13:30-02:00, Su 17:00-24:00",
        "source": "survey",
        "survey:date": "2018-02"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0624229,
          50.6380862
        ]
      },
      "id": "node/5383857951"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5473748412",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/GardenLille/",
        "name": "Garden - bar lounge",
        "source": "survey"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0525615,
          50.6310041
        ]
      },
      "id": "node/5473748412"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5509181235",
        "amenity": "bar",
        "contact:website": "http://www.lefarafina.fr",
        "name": "Farafina",
        "opening_hours": "Tu-We 17:00-01:00; Th-Sa 17:00-03:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0588421,
          50.6292485
        ]
      },
      "id": "node/5509181235"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5538696774",
        "amenity": "bar",
        "name": "O Paradyz",
        "source": "survey",
        "survey:date": "2017-04"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0548544,
          50.6328905
        ]
      },
      "id": "node/5538696774"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5546519609",
        "amenity": "bar",
        "level": "0",
        "name": "L Atelier Royal",
        "toilets": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0583014,
          50.6393518
        ]
      },
      "id": "node/5546519609"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5577104562",
        "amenity": "bar",
        "name": "Le Sebasto",
        "shop": "tobacco",
        "source": "survey"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0588046,
          50.6295782
        ]
      },
      "id": "node/5577104562"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5600644293",
        "addr:city": "Lille",
        "addr:housenumber": "5",
        "addr:street": "Place Louise de Bettignies",
        "amenity": "bar",
        "name": "L Imaginaire",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0642612,
          50.6404504
        ]
      },
      "id": "node/5600644293"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5613162229",
        "addr:housenumber": "79",
        "addr:postcode": "59000",
        "addr:street": "Rue Jacquemars Giélée",
        "amenity": "bar",
        "name": "Chez Xav",
        "website": "https://www.chezxav.com/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0546749,
          50.6340152
        ]
      },
      "id": "node/5613162229"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5651574021",
        "addr:housenumber": "21",
        "addr:postcode": "59170",
        "addr:street": "Rue de la Gare",
        "amenity": "bar",
        "name": "Le Frederick s pub",
        "name:fr": "Frederick s pub",
        "phone": "+33983305843",
        "website": "https://m.facebook.com/Frederickspub"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.145525,
          50.6745478
        ]
      },
      "id": "node/5651574021"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5706211024",
        "amenity": "bar",
        "level": "0",
        "name": "Le Triporteur"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0321225,
          50.6447922
        ]
      },
      "id": "node/5706211024"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5768108634",
        "amenity": "bar",
        "name": "Fifi s Wine Bar",
        "opening_hours": "Tu-Sa 18:00-3:00",
        "phone": "+33 68 1597582",
        "website": "https://www.fifiswinebar.fr/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0580564,
          50.6387159
        ]
      },
      "id": "node/5768108634"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5788114760",
        "amenity": "bar",
        "level": "0",
        "name": "L Antre de Lomme",
        "opening_hours": "Tu-Th 17:00-23:00; Fr 17:00-01:00, Sa 17:00-02:00",
        "outdoor_seating": "yes",
        "wheelchair": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0052031,
          50.6471367
        ]
      },
      "id": "node/5788114760"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5853256607",
        "addr:city": "Lille",
        "addr:housenumber": "37",
        "addr:postcode": "59000",
        "addr:street": "Rue des Postes",
        "amenity": "bar",
        "name": "La Griffe"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0572957,
          50.6270851
        ]
      },
      "id": "node/5853256607"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5894248706",
        "amenity": "bar",
        "name": "Riddim"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0549692,
          50.6242177
        ]
      },
      "id": "node/5894248706"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5894474285",
        "amenity": "bar",
        "name": "Chicha Purple"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0530345,
          50.6323118
        ]
      },
      "id": "node/5894474285"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5915592426",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/oasis.lille",
        "food": "yes",
        "name": "L Oasis",
        "opening_hours": "Tu-Su 11:30-23:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0493143,
          50.6380716
        ]
      },
      "id": "node/5915592426"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5942418325",
        "amenity": "bar",
        "name": "Le Yacht"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0642991,
          50.6330361
        ]
      },
      "id": "node/5942418325"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/5956476491",
        "addr:city": "Lille",
        "addr:housenumber": "12",
        "addr:postcode": "59000",
        "addr:street": "Place Déliot",
        "amenity": "bar",
        "name": "Level Up"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0680059,
          50.6199148
        ]
      },
      "id": "node/5956476491"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6032922285",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/Camdenbar.Lille",
        "name": "Camden Bar",
        "opening_hours": "Mo-Tu 17:00-24:00; Fr 17:00-01:00; Sa 17:00-02:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0561867,
          50.6457523
        ]
      },
      "id": "node/6032922285"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6119981564",
        "amenity": "bar",
        "level": "0",
        "name": "Le Midland",
        "survey:date": "2019-05",
        "toilets": "yes",
        "website": "https://facebook.com/LeMidland/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0650166,
          50.62002
        ]
      },
      "id": "node/6119981564"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6135647786",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/lesfrerespinardlille/",
        "contact:phone": "+33 3 20 55 62 67",
        "contact:website": "http://www.lesfrerespinard.com/",
        "name": "Les frères pinard"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0608357,
          50.640474
        ]
      },
      "id": "node/6135647786"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6167915386",
        "amenity": "bar",
        "name": "Bartown"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0563629,
          50.6464345
        ]
      },
      "id": "node/6167915386"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6167920552",
        "amenity": "bar",
        "name": "Barnett’s Lille"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0572737,
          50.646704
        ]
      },
      "id": "node/6167920552"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6167924971",
        "amenity": "bar",
        "name": "The level"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0574969,
          50.6467689
        ]
      },
      "id": "node/6167924971"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6238713786",
        "amenity": "bar",
        "internet_access": "wlan",
        "name": "Kolor",
        "website": "https://www.facebook.com/kolorbarlille/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0555747,
          50.6461831
        ]
      },
      "id": "node/6238713786"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6305966451",
        "addr:street": "Avenue de la République",
        "amenity": "bar",
        "name": "Le Central",
        "wheelchair": "limited"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0145548,
          50.6396575
        ]
      },
      "id": "node/6305966451"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6387362442",
        "amenity": "bar",
        "level": "0",
        "name": "Le Rouge"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0537538,
          50.646508
        ]
      },
      "id": "node/6387362442"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6404723398",
        "amenity": "bar",
        "contact:phone": "+33 7 60 05 72 93",
        "contact:website": "https://www.facebook.com/joysbarlille/",
        "name": "Joy s Bar"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0586082,
          50.6437695
        ]
      },
      "id": "node/6404723398"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6415778697",
        "amenity": "bar",
        "contact:website": "http://www.bierbuik.fr/",
        "cuisine": "regional",
        "name": "BierBuik - Bloemeke"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0582433,
          50.6394016
        ]
      },
      "id": "node/6415778697"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6425860475",
        "amenity": "bar",
        "contact:website": "https://www.facebook.com/AfterTimesLille/",
        "name": "After Time s",
        "survey:date": "2019-04"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0541788,
          50.6325466
        ]
      },
      "id": "node/6425860475"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6425860476",
        "amenity": "bar",
        "cocktails": "yes",
        "contact:facebook": "https://www.facebook.com/LANKA-bar-108679840469811/",
        "name": "Lanka Bar",
        "survey:date": "2020-12"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0543079,
          50.6324874
        ]
      },
      "id": "node/6425860476"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6427720560",
        "amenity": "bar",
        "name": "L Estaminet"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0405676,
          50.6312703
        ]
      },
      "id": "node/6427720560"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6427720561",
        "amenity": "bar",
        "contact:phone": "+33 3 20 93 58 09",
        "food": "yes",
        "name": "Le Pearl"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0403991,
          50.6314126
        ]
      },
      "id": "node/6427720561"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6431771374",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/deliriumcafelille/",
        "contact:instagram": "https://www.instagram.com/deliriumcafelille/",
        "name": "Delirium Café",
        "opening_hours": "Mo-Th 16:00-23:45; Fr 16:00-00:45; Sa 16:00-01:45; Su 09:00-23:45",
        "survey:date": "2019-04"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0548087,
          50.6324216
        ]
      },
      "id": "node/6431771374"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6431771387",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/La-Blonde-425154964355663/",
        "contact:phone": "+33 3 28 04 97 38",
        "name": "La Blonde"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0584606,
          50.6382788
        ]
      },
      "id": "node/6431771387"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6431771400",
        "amenity": "bar",
        "name": "African Children",
        "survey:date": "2019-04"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0586141,
          50.6388555
        ]
      },
      "id": "node/6431771400"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6488361862",
        "amenity": "bar",
        "name": "sling"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0732549,
          50.6221872
        ]
      },
      "id": "node/6488361862"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6512912118",
        "amenity": "bar",
        "contact:website": "http://noaobarlille.com",
        "food": "yes",
        "name": "Noao",
        "opening_hours": "Tu-Th 17:00-00:00; Fr 17:00-01:00; Sa 15:00-01:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0594839,
          50.6390063
        ]
      },
      "id": "node/6512912118"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6571108767",
        "addr:city": "Lille",
        "addr:housenumber": "57",
        "addr:postcode": "59800",
        "addr:street": "Rue Basse",
        "amenity": "bar",
        "cocktails": "yes",
        "contact:facebook": "https://www.facebook.com/le.so.bar",
        "name": "Le So Bar",
        "phone": "+33 3 20 13 17 51",
        "survey:date": "2019-06"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0606449,
          50.638666
        ]
      },
      "id": "node/6571108767"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6571108769",
        "addr:city": "Lille",
        "addr:housenumber": "51",
        "addr:postcode": "59800",
        "addr:street": "Rue Basse",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/PostArriere/",
        "contact:phone": "+33 3 20 56 03 27",
        "name": "Post Arrière",
        "survey:date": "2019-06"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0610523,
          50.6387005
        ]
      },
      "id": "node/6571108769"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6578979501",
        "amenity": "bar",
        "name": "Tír na nÓg",
        "outdoor_seating": "yes",
        "phone": "+33 3 20 54 66 69",
        "website": "http://www.tirnanog.fr/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0608293,
          50.6272099
        ]
      },
      "id": "node/6578979501"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6651598741",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/La.Confrerie.Bar.Etudiant",
        "name": "La Confrérie"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0429015,
          50.6324424
        ]
      },
      "id": "node/6651598741"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6696678464",
        "addr:city": "Lille",
        "addr:housenumber": "11",
        "addr:street": "Place Jacquart",
        "amenity": "bar",
        "food": "yes",
        "name": "Le Boucan",
        "opening_hours": "Mo,Tu 10:30-15:00; We 10:30-18:30; Th 10:30-23:30; Fr 10:30-23:45",
        "phone": "+33 3 20 54 68 02",
        "website": "https://www.facebook.com/LisonEtMarie/",
        "wheelchair": "limited"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0643092,
          50.631582
        ]
      },
      "id": "node/6696678464"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6866906211",
        "addr:city": "Lille",
        "addr:housenumber": "18",
        "addr:postcode": "59800",
        "addr:street": "Rue de Gand",
        "amenity": "bar",
        "name": "Beerchope",
        "opening_hours": "Su-Th 17:00-00:00; Fr 17:00-01:00; Sa 17:00-02:00",
        "phone": "+33 6 79 40 85 33"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.065685,
          50.6415798
        ]
      },
      "id": "node/6866906211"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6866906212",
        "addr:city": "Lille",
        "addr:housenumber": "14",
        "addr:postcode": "59800",
        "addr:street": "Rue de Gand",
        "amenity": "bar",
        "name": "La Biche & le Renard",
        "opening_hours": "Su, Tu-Th 14:00-00:00; Fr 14:00-01:00; Sa 14:00-02:00",
        "phone": "+33 6 45 50 39 65"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0656215,
          50.6415024
        ]
      },
      "id": "node/6866906212"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6866906213",
        "addr:city": "Lille",
        "addr:housenumber": "11",
        "addr:postcode": "59800",
        "addr:street": "Rue de Gand",
        "amenity": "bar",
        "contact:facebook": "https://fr-fr.facebook.com/le.so.bar",
        "name": "Le So Bar À Mojitos 2"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0655411,
          50.6416607
        ]
      },
      "id": "node/6866906213"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6892270503",
        "addr:city": "Lille",
        "addr:housenumber": "358",
        "addr:postcode": "59000",
        "addr:street": "Rue Léon Gambetta",
        "amenity": "bar",
        "name": "Bar de la Paix"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0484099,
          50.6269491
        ]
      },
      "id": "node/6892270503"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/6954037071",
        "addr:city": "Lille",
        "addr:housenumber": "321",
        "addr:postcode": "59000",
        "addr:street": "Rue Léon Gambetta",
        "amenity": "bar",
        "name": "Le Stout"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.050122,
          50.6274647
        ]
      },
      "id": "node/6954037071"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7063737810",
        "addr:city": "Marcq-en-Barœul",
        "addr:housenumber": "90",
        "addr:postcode": "59700",
        "addr:street": "Avenue du Maréchal Foch",
        "amenity": "bar",
        "name": "O Mulligans",
        "opening_hours": "Mo-Th 11:45-00:00; Fr 11:45-01:00; Sa 16:30-02:00; Su 11:00-00:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.094767,
          50.6742542
        ]
      },
      "id": "node/7063737810"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7066417867",
        "addr:city": "Lille",
        "addr:housenumber": "94",
        "addr:postcode": "59800",
        "addr:street": "Rue Pierre Mauroy",
        "amenity": "bar",
        "name": "Le Noailles",
        "opening_hours": "Mo-Sa 08:00-20:00",
        "phone": "+33 3 20 57 27 23",
        "sells:tobacco": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0670574,
          50.635085
        ]
      },
      "id": "node/7066417867"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7199946903",
        "amenity": "bar",
        "name": "Le Yéti"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0548625,
          50.6308852
        ]
      },
      "id": "node/7199946903"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7283283272",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/foolille/",
        "name": "Fool",
        "opening_hours": "Mo-Th 16:00-00:00; Fr 16:00-01:00; Sa 16:00-02:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0633789,
          50.6347587
        ]
      },
      "id": "node/7283283272"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7305511495",
        "amenity": "bar",
        "old_name": "Le petit Wally s"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.062194,
          50.6275098
        ]
      },
      "id": "node/7305511495"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7335390033",
        "amenity": "bar",
        "name": "Café de la Mairie"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.077196,
          50.6058878
        ]
      },
      "id": "node/7335390033"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7442520036",
        "addr:city": "Lille",
        "addr:housenumber": "26-28",
        "addr:postcode": "59800",
        "addr:street": "Place Louise de Bettignies",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/Mamamouchi-526068727764872/",
        "name": "Mamamouchi",
        "phone": "+33 9 50 85 93 36"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0652574,
          50.6410741
        ]
      },
      "id": "node/7442520036"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7442763320",
        "addr:city": "Lille",
        "addr:housenumber": "18",
        "addr:postcode": "59000",
        "addr:street": "Rue Saint-Jacques",
        "amenity": "bar",
        "contact:facebook": "https://fr-fr.facebook.com/Box2BoxLille/",
        "name": "Box2Box",
        "phone": "+33 6 44 64 71 95",
        "website": "https://www.box2box.fr/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0657995,
          50.64044
        ]
      },
      "id": "node/7442763320"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7444485000",
        "addr:city": "Lille",
        "addr:housenumber": "36",
        "addr:postcode": "59800",
        "addr:street": "Place Louise de Bettignies",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/Le-Django-101503501272286/",
        "name": "Le Django",
        "phone": "+33 6 99 45 42 54",
        "sells:tobacco": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0653278,
          50.6415941
        ]
      },
      "id": "node/7444485000"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7444485001",
        "addr:city": "Lille",
        "addr:housenumber": "20",
        "addr:postcode": "59800",
        "addr:street": "Rue de Gand",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/DjangoBeerLille/",
        "name": "Django Beer",
        "phone": "+33 6 99 45 42 54"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0657114,
          50.6416154
        ]
      },
      "id": "node/7444485001"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7444485010",
        "addr:city": "Lille",
        "addr:housenumber": "30",
        "addr:postcode": "59800",
        "addr:street": "Rue de Gand",
        "amenity": "bar",
        "contact:facebook": "https://fr-fr.facebook.com/Monsieur-Jacques-Bar-%C3%A0-vins-200186756659204/",
        "name": "Monsieur Jacques",
        "phone": "+33 3 20 74 85 59"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0659353,
          50.6418926
        ]
      },
      "id": "node/7444485010"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7448518935",
        "addr:city": "Lille",
        "addr:housenumber": "8",
        "addr:postcode": "59800",
        "addr:street": "Place de Gand",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/La-Petite-Place-395250411314989/",
        "name": "La Petite Place",
        "phone": "+33 6 30 00 00 46"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0675753,
          50.643092
        ]
      },
      "id": "node/7448518935"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7448518936",
        "addr:city": "Lille",
        "addr:housenumber": "74",
        "addr:postcode": "59800",
        "addr:street": "Rue de Gand",
        "amenity": "bar",
        "brewery": "various",
        "contact:facebook": "https://fr-fr.facebook.com/augandbrinus/",
        "name": "Au Gand Brinus",
        "phone": "+33 6 30 30 40 98"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0675914,
          50.6432528
        ]
      },
      "id": "node/7448518936"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7457900797",
        "addr:city": "Lille",
        "addr:housenumber": "55",
        "addr:postcode": "59800",
        "addr:street": "Rue Basse",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/bernadettelille/",
        "name": "Bernadette"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.060709,
          50.6386707
        ]
      },
      "id": "node/7457900797"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7457900801",
        "addr:city": "Lille",
        "addr:housenumber": "67",
        "addr:postcode": "59800",
        "addr:street": "Rue Basse",
        "amenity": "bar",
        "cocktails": "yes",
        "contact:facebook": "https://fr-fr.facebook.com/ledandylille",
        "name": "Le Dandy",
        "opening_hours": "Mo-Th 17:00-00:00; Fr 19:00-01:00; Sa 15:00-02:00",
        "phone": "+33 3 20 51 50 01"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0603241,
          50.6386332
        ]
      },
      "id": "node/7457900801"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7467898593",
        "addr:city": "Lille",
        "addr:housenumber": "16",
        "addr:postcode": "59800",
        "addr:street": "Rue Thiers",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/RestaurantMademoiselle/",
        "name": "Mademoiselle",
        "phone": "+33 3 20 10 09 90",
        "website": "https://www.mademoiselle-resto.com/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0590535,
          50.6382328
        ]
      },
      "id": "node/7467898593"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7467944480",
        "addr:city": "Lille",
        "addr:housenumber": "2",
        "addr:postcode": "59800",
        "addr:street": "Place Maurice Schumann",
        "amenity": "bar",
        "cocktails": "yes",
        "contact:facebook": "https://www.facebook.com/littlehavana.lille/",
        "name": "Little Havana",
        "phone": "+33 3 20 60 34 61",
        "website": "https://www.mesenseignes.fr/little-havana/"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0582073,
          50.6374505
        ]
      },
      "id": "node/7467944480"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7467944481",
        "addr:city": "Lille",
        "addr:housenumber": "6",
        "addr:postcode": "59800",
        "addr:street": "Place Maurice Schumann",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/Au-Boudin-Bar-105454827670365/",
        "name": "Au Boudin Bar",
        "phone": "+33 3 20 54 98 02"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0581094,
          50.6374267
        ]
      },
      "id": "node/7467944481"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7512378940",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/www.peperebar.fr/",
        "name": "Pepere Bar"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0611845,
          50.6294779
        ]
      },
      "id": "node/7512378940"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7614742841",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/Bidule59/",
        "name": "Le bidule",
        "opening_hours": "We-Th 17:30-24:00; Fr 17:30-01:00; Sa 17:30-02:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0555887,
          50.6290365
        ]
      },
      "id": "node/7614742841"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7625813499",
        "addr:city": "Lille",
        "addr:housenumber": "147",
        "addr:street": "Rue du Molinel",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/olocallille",
        "contact:phone": "+33 3 20 54 14 91",
        "food": "yes",
        "name": "O Local",
        "old_name": "Le Loto",
        "opening_hours": "Mo-Fr 09:00-24:00",
        "outdoor_seating": "yes",
        "survey:date": "2020-06"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0636997,
          50.632508
        ]
      },
      "id": "node/7625813499"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7842674308",
        "amenity": "bar",
        "name": "Le Seven"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0992453,
          50.5990213
        ]
      },
      "id": "node/7842674308"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7864519943",
        "amenity": "bar",
        "contact:phone": "+33 3 20 78 52 06",
        "name": "Le Pol Art",
        "smoking": "outside"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.054398,
          50.623514
        ]
      },
      "id": "node/7864519943"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/7876405384",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/Le-W-Wazemmes-101828494569962",
        "name": "Le W"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0484158,
          50.6250831
        ]
      },
      "id": "node/7876405384"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8015857594",
        "amenity": "bar",
        "name": "Ô Papa Bar"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0608258,
          50.6422282
        ]
      },
      "id": "node/8015857594"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8015860199",
        "amenity": "bar",
        "name": "Aux Arts"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0613709,
          50.6418626
        ]
      },
      "id": "node/8015860199"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8261419962",
        "amenity": "bar",
        "name": "Le Lompret"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0094019,
          50.6561563
        ]
      },
      "id": "node/8261419962"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8292679904",
        "addr:city": "Lille",
        "addr:housenumber": "90",
        "addr:postcode": "59000",
        "addr:street": "Rue Pierre Legrand",
        "amenity": "bar",
        "name": "L épi d orge",
        "ref:FR:FINESS": "590021671"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0876876,
          50.6321588
        ]
      },
      "id": "node/8292679904"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8608343240",
        "amenity": "bar",
        "name": "Le Niagara"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0610579,
          50.6194334
        ]
      },
      "id": "node/8608343240"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8632047473",
        "addr:city": "Faches-Thumesnil",
        "addr:housenumber": "17",
        "addr:postcode": "59155",
        "addr:street": "Rue Léon Gambetta",
        "amenity": "bar",
        "name": "Le Doulieu",
        "ref:FR:SIRET": "42051882100012"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0642725,
          50.6090345
        ]
      },
      "id": "node/8632047473"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8730527382",
        "amenity": "bar",
        "brand": "Les BerThoM",
        "contact:website": "https://www.lesberthom.com/les-bars/les-berthom-a-lille/",
        "name": "Les BerThoM - Lille"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.069887,
          50.6251122
        ]
      },
      "id": "node/8730527382"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8839018589",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/barangle95/",
        "contact:phone": "+33 3 20 33 86 41",
        "contact:website": "https://angle95.fr/",
        "name": "Angle 95",
        "opening_hours": "Tu-We 18:00-01:00; Th-Sa 18:00-02:00",
        "outdoor_seating": "yes"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0564899,
          50.6452806
        ]
      },
      "id": "node/8839018589"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8841223798",
        "amenity": "bar",
        "contact:instagram": "https://www.instagram.com/laconfrerieroyale/",
        "name": "La Confrérie Royale",
        "opening_hours": "Mo-Th 15:30-23:30; Fr 15:30-00:30; Sa 15:30-01:30"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0581112,
          50.6395695
        ]
      },
      "id": "node/8841223798"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8853774296",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/urbanbarlilleofficiel",
        "name": "Urban Bar",
        "outdoor_seating": "only"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0633473,
          50.633017
        ]
      },
      "id": "node/8853774296"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8871438117",
        "addr:city": "Lille",
        "addr:street": "Rue du molinel",
        "amenity": "bar",
        "name": "Le Sinclair"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0697784,
          50.6353676
        ]
      },
      "id": "node/8871438117"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8879344754",
        "amenity": "bar",
        "contact:facebook": "https://www.facebook.com/homelille",
        "food": "yes",
        "name": "Home",
        "opening_hours": "Tu-Sa 17:00-00:00; Su 15:00-21:00"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0643496,
          50.623353
        ]
      },
      "id": "node/8879344754"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8893365134",
        "addr:city": "Faches-Thumesnil",
        "addr:housenumber": "37",
        "addr:postcode": "59155",
        "addr:street": "Rue Ferrer",
        "amenity": "bar",
        "name": "Le Dauphin",
        "ref:FR:SIRET": "39962668800036",
        "source": "INSEE - 2021-06"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0650616,
          50.6098169
        ]
      },
      "id": "node/8893365134"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8897991338",
        "addr:city": "Ronchin",
        "addr:housenumber": "698",
        "addr:postcode": "59790",
        "addr:street": "Avenue Jean Jaurès",
        "amenity": "bar",
        "name": "Le Fontenoy",
        "ref:FR:SIRET": "89274390700016",
        "source": "INSEE - 2021-06"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.07684,
          50.6070773
        ]
      },
      "id": "node/8897991338"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8898046110",
        "addr:city": "Ronchin",
        "addr:housenumber": "149",
        "addr:postcode": "59790",
        "addr:street": "Avenue Jean Jaurès",
        "amenity": "bar",
        "name": "Au Petit Chasseur",
        "ref:FR:SIRET": "44041264100027",
        "source": "INSEE - 2021-06"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0758448,
          50.6081367
        ]
      },
      "id": "node/8898046110"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/8907492366",
        "amenity": "bar",
        "name": "La Bulle Café",
        "ref:FR:SIRET": "49020538200024",
        "source": "INSEE - 2021-07",
        "website": "https://maisonsfolie.lille.fr/la-bulle-cafe"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.0679998,
          50.6229824
        ]
      },
      "id": "node/8907492366"
    }
  ]
}
	'.